### ISSUE TITLE
Explore: Research existing alternatives of DSS

### ISSUE THREAD

**Issue by misohu** [canonical/data-science-stack#14]
### Why it needs to get done

We need more insights on how others are solving problems which we want to face with DSS.

### What needs to get done

Research existing tools:
- https://github.com/replicate/cog
- https://github.com/tensorchord/envd

### When is the task considered done

We know what are aforementioned tools doing and how they are doing that.

**Comment by misohu** [comment]
### COG
Tool which allows you to pack ML models into containers. This tool handles only prediction/inference phase not the training phase. It answers the questions "What is the correct way to pack my trained model into a production container and how should I serve it". Key functionality:
- pack the ML code into Docker container 
- Cuda and cuDNN drivers will be handled for you
- Handles the serving part for you using FastAPI
- handles the queue part for you (e.g. for batch processing)

This tool does not handle the nvidia driver problem only Cuda and cuDNN. The way they handle Cuda and cuDNN is as follows. When specifying your code for the image you write a yaml file e.g.
```
build:
  gpu: true
  system_packages:
    - "libgl1-mesa-glx"
    - "libglib2.0-0"
  python_version: "3.11"
  python_packages:
    - "tensorflow==2.15.0"
predict: "predict.py:Predictor"
```
You also need to provide python code for the prediction in this case for `predict.py`. Their tool will then query tensorflow's documentation page https://www.tensorflow.org/install/source#gpu and it will generate the driver version matrix from which it picks the latest one. They do the same for Torch and pure cuda.

**Key differences to DSS**
- they don't handle training 
- they don't provide notebooks or any workplace
- they don't solve the nvidia driver problem on host machine 
- they don't provide model registry
